#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

function generateMarkdown(imageFolder, outputFile, repoUrl, header, description, disclaimer) {
    const imageExtensions = ['.jpg', '.jpeg', '.png', '.gif'];
    
    let content = `${header}\n${description}\n\n${disclaimer}\n# Preview\n`;
    content += '| Column 1 | Column 2 | Column 3 | Column 4 |\n';
    content += '|---------|---------|---------|---------|\n';

    let counter = 0;
    let row = '';

    const files = fs.readdirSync(imageFolder);
    
    for (const file of files) {
        const filePath = path.join(imageFolder, file);
        const ext = path.extname(file).toLowerCase();
        
        if (fs.statSync(filePath).isFile() && imageExtensions.includes(ext)) {
            const url = `${repoUrl}/${imageFolder}/${file}`;
            row += `| ![${file}](${url}) `;
            counter++;
            
            if (counter === 4) {
                content += `${row}|\n`;
                row = '';
                counter = 0;
            }
        }
    }

    if (counter !== 0) {
        while (counter < 4) {
            row += '| ';
            counter++;
        }
        content += `${row}|\n`;
    }

    fs.writeFileSync(outputFile, content);
    console.log(`Markdown file '${outputFile}' generated successfully.`);
}

function commitAndPush(imageFolder) {
    const originalDir = process.cwd();
    
    try {
        process.chdir(imageFolder);
        execSync('git add .', { stdio: 'inherit' });
        execSync('git commit -m "this commit was automatically generated by a script uwu"', { stdio: 'inherit' });
        execSync('git push', { stdio: 'inherit' });
    } finally {
        process.chdir(originalDir);
    }
}

const baseUrl = 'https://raw.githubusercontent.com/krymancer';
const header = '# Wallpapers';
const description = "This is my repository of wallpapers which I've collected over the years. A catppuccin-mocha version is available [here](https://github.com/orangci/walls-catppuccin-mocha).";
const disclaimer = "> Disclaimer: These wallpapers are sourced from many, many, many sources on the internet. I did not make any of these, although I have *edited* several of them a little bit. Zero credit belongs to me in that regard, I'm simply the collector. If you are the artist of one of these wallpapers, please **contact me**, I will happily take the wallpaper down or add credit in this README.";

generateMarkdown('wallpapers', 'wallpapers/README.md', `${baseUrl}`, header, description, disclaimer);
